language: python
python:
  - "3.6"
install:
  - cd back-end
  - pip install -r requirements.txt
  - django-admin.py startproject ticket
  - python manage.py startapp ai
  - python manage.py migrate
script:
  - python manage.py test ai
